baseURL = 'http://noizy.cloud/'
languageCode = 'en'
title = 'Microsoft Security & Incident Response'
theme = 'congo'

defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]