baseURL = 'http://noizy.cloud/'

title = 'Microsoft Security & Incident Response'
theme = 'congo'

languageCode = 'en'
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 400

[outputs]
  home = ["HTML", "RSS", "JSON"]