baseURL = 'http://noizy.cloud/'

title = 'Microsoft Security & Incident Response'
theme = 'hugo-clarity-master'

languageCode = 'en'
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 15
summaryLength = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]